title: Anna Kirkby
remote_theme: chrisrhymes/bulma-clean-theme
favicon: https://github.com/annakirkby.png
paginate: 5
paginate_path: "/colouring/page:num"

defaults:
  -
    scope:
      path: ""
    values:
      hero_image: /images/hero.jpg
      hero_darken: True
