title: Anna Kirkby
remote_theme: chrisrhymes/bulma-clean-theme
paginate: 5
paginate_path: "/colouring/page:num"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      hero_image: /images/hero.jpg
